name: CI

on:
  push:
    branches: ["**"]
  workflow_dispatch:
  pull_request:

jobs:
  build_test:
    uses: membraneframework-labs/membrane-actions/.github/workflows/build-test.yml@main

  test:
    uses: membraneframework-labs/membrane-actions/.github/workflows/test.yml@main

  lint:
    uses: membraneframework-labs/membrane-actions/.github/workflows/lint.yml@main
